@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=WindowExtensions
SET APPDESCRIPTION=Window Extensions Menu and HotKeys
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=Icons\windows.ico

CALL BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
