@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=WindowMenu
SET APPDESCRIPTION=Window Management Menu
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=windows.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
